### ISSUE TITLE
[Bug] Possible incompat with other mods [Connector Forge 1.20.1]

### ISSUE THREAD

**Issue by YnwLNE** [TimVincii/Terrastorage#10]
### What happened?

Creates a failed to join error when loading into a world, by itself it works just fine so I'm assuming it's some mod conflict 
I'll do a large sample binary search when I have the free time but hopefully latest can point some things out.

additional mods that aren't in the pastebin due to word count limit: 
![image](https://github.com/user-attachments/assets/e363fcbc-95ea-4c19-9a4f-70a9e37d0604)

### Terrastorage Version

1.1.4

### Fabric API Version

Forgified Fabric API 0.92.2

### Minecraft Version

1.20.1

### Relevant Log Output

```shell
https://mclo.gs/H4tP8N5
```

### Other Mods

```shell
https://pastebin.com/yZPRdx5H
```

**Comment by TimVincii** [comment]
Hi! thanks a lot for taking the time to report this issue, and for offering to do a binary search on the mods. That would be extremely helpful in pinpointing the root cause.

I'd love to be able to test things out on my own, but with the number of mods you're using, gathering them all manually would be quite the challenge. If it happens to be part of a modpack, that would simplify things quite a bit. If not, would it be possible for you to upload a zip or rar archive of your mods to a file-sharing platform like Google Drive or Mega? this would make testing on my end a lot more doable.

Let me know if that's possible, and thanks again for your time in reporting this bug.

**Comment by NattoRiisa** [comment]
config conflict too perhaps? what if you sent those too...

**Comment by YnwLNE** [comment]
> Hi! thanks a lot for taking the time to report this issue, and for offering to do a binary search on the mods. That would be extremely helpful in pinpointing the root cause.
> 
> I'd love to be able to test things out on my own, but with the number of mods you're using, gathering them all manually would be quite the challenge. If it happens to be part of a modpack, that would simplify things quite a bit. If not, would it be possible for you to upload a zip or rar archive of your mods to a file-sharing platform like Google Drive or Mega? this would make testing on my end a lot more doable.
> 
> Let me know if that's possible, and thanks again for your time in reporting this bug.

https://drive.google.com/file/d/1eHjiq6fZF8WtXmm8zNRWO2curFUEGHz2/view?usp=sharing here you go, it's quite big, my bad. I know the other arrows are there but I intended to disable them in favor of your mod (if I can find which it is). But I know whichever mod it is, it's not the problematic one

**Comment by TimVincii** [comment]
Hi again! Thanks for uploading the mods and configs. I tested it on Forge 1.20.1 - 47.3.0, and everything seemed to work fine on my end. I created and joined a new world without any errors during loading.

The issue might be specific to your world setup. Could you try creating a new world to see if the error still happens there? If possible, a screenshot of the error screen might also help pinpoint the problem.

And don’t worry about the mod list size, it's totally fine. Just let me know if there’s any other detail you think might help.

**Comment by YnwLNE** [comment]
I don't know what to say, it was happening on every world I created (failed to join server with a long error) and only with this mod installed and I could replicate it perfectly each time. Now everything is seemingly fine? Idk if this is more concerning or a blessing but I'll close this issue for now

**Comment by TimVincii** [comment]
Glad to hear everything’s working now! It’s possible the initial issue resolved itself after a PC restart or due to some other unrelated factor. If you ever run into this issue again, please feel free to reopen this issue, have an awesome day!
