### ISSUE TITLE
[Suggestion] I made a Resource Pack :)

### ISSUE THREAD

**Issue by VentgirlJoanne** [TimVincii/Terrastorage#16]
### Description

Hi! So this isn't really a suggestion but it felt even less like a bug or a question.

Anyway I made a vanilla UI styled resource pack for my own use in my modded singleplayer world and although i don't generally post my packs online I thought as the dev you'd be interested in seeing it. 
![terrastorage rp ui demonstration](https://github.com/user-attachments/assets/3989f00b-5108-4999-b9cb-940c669925fb)
[Vanilla Style Terrastorage UI.zip](https://github.com/user-attachments/files/18254890/Vanilla.Style.Terrastorage.UI.zip)

Thanks for the awesome mod :)

**Comment by LydiaLambda** [comment]
Ooo, I really like your updated icons, looks great! I feel like it matches the base game a bit better. Thanks for sharing!!

Also, I'm curious now, what mods do you play with?

**Comment by TimVincii** [comment]
Hey, this looks really cool! Thanks so much for taking the time to share it.

As Lydia mentioned, these icons really match the base game’s style better, and I personally think they’re fantastic.

With that in mind, would you be interested in having them officially added to Terrastorage? I’ve thought it over, and I’d be more than happy to include an option to toggle between these and the existing Terraria ones. Because these are so much more in line with Minecraft’s aesthetic, I’d actually like to make them the default option.

Of course, I’ll credit you for the icons both in the mod’s description and anywhere else it’s relevant. Let me know what you think!

**Comment by VentgirlJoanne** [comment]
Oh yeah I'd be honored! I don't really have any links or anything to reference credit bc as I said i usually keep my stuff to myself and friends, but just crediting Ventgirl_Joanne in the mod page and resource pack description would be cool. Right now its just my placeholder smiley pack.mcmeta but if you could say "textures by Ventgirl_Joanne" or some such that would be cool!

**Comment by TimVincii** [comment]
> Oh yeah I'd be honored! I don't really have any links or anything to reference credit bc as I said i usually keep my stuff to myself and friends, but just crediting Ventgirl_Joanne in the mod page and resource pack description would be cool. Right now its just my placeholder smiley pack.mcmeta but if you could say "textures by Ventgirl_Joanne" or some such that would be cool!

Awesome! I'll start working on it this weekend.
I'll now close this issue as completed, but if you have anything to add feel free to comment here again.

Have a great day!

**Comment by TimVincii** [comment]
Hey again, as of version 1.2.3 Terrastorage uses your awesome textures as the default for the Sort Inventory and Quick Stack To Nearby Storages buttons.

I've credited you in an Acknowledgments section in the mod's page, let me know if you want me to tweak anything.
I'll also make sure to update the Sort Inventory and Quick Stack To Nearby Storages preview gif to showcase the updated textures, just didn't have time to do it this week.

Have a great day!

**Comment by VentgirlJoanne** [comment]
Hey looks awesome and really appreciate the credit on the mod page!

Minor question though is if you were planning and also adding my "favorite item" icon background as well? I don't want to overreach if that was an intentional exclusion, (I won't be offended if it is, i tried a whole lot of different textures for that and still feel its not quite right) but it is subtle and the screenshot I sent above does have other mods present so thought it was possible you just missed it.

Either way, really happy to be able to contribute!

**Comment by TimVincii** [comment]
Hey, I should have addressed that in the earlier update but I was in a rush and just forgot, sorry about that.

To be honest I did miss it at first, but I did notice it after downloading the pack.
The icons of the buttons had a very strong Minecraft vibe, and so I immediately though of adding them as a part of a Minecraft style.

I did really like the favorite icon, it's clean and neat, but it didn't really fit that Minecraft style, so I decided not to add it for now.

That said, as I mentioned in the release notes, I do plan on making a buttons customization screen for the inventory storage option buttons in the future, which will house many more customization options.
I also plan on adding the customization of the favorite item border as part of that screen, and I'll add your icon as an option.

Please do note that it will take some time for that screen to be ready and released in an update, but I'll do my best.

Again, sorry for not clarifying all of this in the earlier update and kind of leaving you in the dark, and have a great day!
