### ISSUE TITLE
[Bug] Mod incompatibilities with the BlockEntityRenderer changes in 1.0.4

### ISSUE THREAD

**Issue by BlindTwig** [TimVincii/Terrastorage#4]
### What happened?

Hello again, found some mods that crash the game upon startup with the new block entity renderer stuff you've done in 1.0.4, although it's not a traditional crash that generates a log, just has a Fabric Loader crash window, so the logs are very short. Each one is named after the incompatible mod.
[crayfishfurniture_crash.txt](https://github.com/user-attachments/files/17153825/crayfishfurniture_crash.txt)
[amendments_crash.txt](https://github.com/user-attachments/files/17153826/amendments_crash.txt)

### Terrastorage Version

1.0.4

### Fabric API Version

0.102.0

### Minecraft Version

1.21

**Comment by TimVincii** [comment]
Hey! once again thanks for taking the time to report these bugs, truly appreciate it.
Took a good look at both logs, while the specific error in each case is different, the overall cause is indeed the new `BlockEntityRendererManager` class that was added alongside other changes in version 1.0.4.

I just released version 1.0.5 which adds error handling to the specific code block that causes these issues, I also went ahead and verified that the crashes no longer happen, so this update should resolve the issues.
Thanks again for the report, and I hope you have a great day!

**Comment by Carsonated** [comment]
Is it possible to get this working with Sinytra Connector?

**Comment by TimVincii** [comment]
> Is it possible to get this working with Sinytra Connector?

Hey! I had someone ask me about this on CurseForge but completely forgot about this, my bad.
I just released version 1.1.1] for Minecraft 1.21 and 1.21.1 that makes Terrastorage compatible with Sinytra Connector:

* [Version 1.1.1 (Modrinth)](https://modrinth.com/mod/terrastorage/version/1.1.1+1.21-1.21.1)
* [Version 1.1.1 (CurseForge)](https://www.curseforge.com/minecraft/mc-mods/terrastorage/files/5847562)

The client no longer crashes on startup, and everything seems to be working properly.
However, note that my testing was very brief, and it's possible there were issues that I simply missed.

Let me know if there's anything else I can help with and have a great day!

**Comment by Carsonated** [comment]
> > Is it possible to get this working with Sinytra Connector?
> 
> Hey! I had someone ask me about this on CurseForge but completely forgot about this, my bad. I just released version 1.1.1 for Minecraft 1.21 and 1.21.1 that makes Terrastorage compatible with Sinytra Connector:
> 
> * [Version 1.1.1 (Modrinth)](https://modrinth.com/mod/terrastorage/version/1.1.1+1.21-1.21.1)
> * [Version 1.1.1 (CurseForge)](https://www.curseforge.com/minecraft/mc-mods/terrastorage/files/5847562)
> 
> The client no longer crashes on startup, and everything seems to be working properly. However, note that my testing was very brief, and it's possible there were issues that I simply missed.
> 
> Let me know if there's anything else I can help with and have a great day!

thank you for your work, I really enjoy your mod!
