### ISSUE TITLE
[Question] I love the banner for the mod! 

### ISSUE THREAD

**Issue by Dreuzz** [TimVincii/Terrastorage#5]
### Your Question

How did you make it? Also what font?

**Comment by TimVincii** [comment]
Hey, glad you liked it!
I made it using Adobe Photoshop 2023, a friend of mine helped a lot.

The fonts used are:
* Title - Rubik [Bold], available on [google fonts](https://fonts.google.com/specimen/Rubik).
* Subtitle - Corbel [Light], a part of the Microsoft ClearType font collection, which means it's included with Microsoft Office and certain versions of Windows.

Let me know If you're interested in other parts of the banner and have Adobe Photoshop, I'll be happy to provide the psd file!

**Comment by Dreuzz** [comment]
Yes I have Photoshop (ifykyk) I would really like to make a banner similiar to this for my modpack!

**Comment by TimVincii** [comment]
Great! GitHub doesn't support uploading psd files to comments, so I've uploaded it to google drive instead:
https://drive.google.com/file/d/17rKx6tE4V7JTfSOO3fdrlODgVROer9LN/view?usp=sharing

Let me know if you need anything else!
